### ISSUE TITLE
Picture still uploading not finishing what is this problem

### ISSUE THREAD

**Issue by punisher-303** [prajwalpkp2106/Tango_flutter#1]
![image](https://github.com/user-attachments/assets/e8a74fb4-f98e-4122-895e-47c499af31b9)

**Comment by prajwalpkp2106** [comment]
Is the firebase correctly configured ?
there may be an issue in pushing the data on firebase
below is an example of my data base
![image](https://github.com/user-attachments/assets/5ee8cac1-40c7-4eb3-a31d-7cb8266007a7)
![image](https://github.com/user-attachments/assets/65326509-0f8f-4fd0-ac3f-755f305d21d5)
![image](https://github.com/user-attachments/assets/0b9d9f83-73bb-4663-9912-0e19525d2149)
![image](https://github.com/user-attachments/assets/392c8022-4960-440d-a8cd-b70b080bf8ba)
